# Generated by Django 2.2.2 on 2019-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Pwd',
            field=models.CharField(max_length=20),
        ),
    ]
